### ISSUE TITLE
reloading constantly

### ISSUE THREAD

**Issue by tujeff** [gitpod-io/openvscode-server#350] opened 2022-05-13 15:44 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.67.0
- OS Version: Linux Bullseye

Steps to Reproduce:

1. constantly reloading
2. Only happen on version 1.67.0

After upgrade from version 1.66.1 to the latest 1.67.0, the screen reloading automatically constantly.

**Comment by jeanp413** [comment] 2022-05-13 17:09
Hi @tujeff do you see some error in the dev tools console or the server logs in terminal?

**Comment by tujeff** [comment] 2022-05-13 17:37
<img width="1896" alt="Screen Shot 2022-05-13 at 10 36 21 AM" src="https://user-images.githubusercontent.com/67305851/168337772-3c265e5f-11c2-492e-a63d-0bf2d33872ff.png">

**Comment by tujeff** [comment] 2022-05-13 17:50
This is from the server logs, with 1.67.0

<img width="1186" alt="Screen Shot 2022-05-13 at 10 47 36 AM" src="https://user-images.githubusercontent.com/67305851/168339544-95ed59b5-abf7-48ff-8102-8f297ba908e4.png">

**Comment by jeanp413** [comment] 2022-05-13 18:01
I've seen this `1006` error when there's some misconfiguration on the reverse proxy [[1](https://github.com/gitpod-io/openvscode-server/issues/317)] [[2](https://github.com/gitpod-io/openvscode-server/discussions/96)] did you change something else other than updating openvscode-server?
Also could you try removing all extensions in the `/home/student/.openvscode-server/extensions` folder first before launching the server

**Comment by tujeff** [comment] 2022-05-13 18:12
I did not change reverse proxy. This is after removed all extensions. 1.67.0

<img width="1186" alt="Screen Shot 2022-05-13 at 11 09 59 AM" src="https://user-images.githubusercontent.com/67305851/168342916-badd0711-6510-471f-851a-abc9e28c0559.png">

**Comment by tujeff** [comment] 2022-05-13 18:15
This is 1.66.1, has no reloading on Management...

<img width="1248" alt="Screen Shot 2022-05-13 at 11 13 45 AM" src="https://user-images.githubusercontent.com/67305851/168343237-af73d7d8-3a30-4f6d-abb9-5bf1f01268a0.png">

**Comment by tujeff** [comment] 2022-05-13 18:19
1006 has been there for a while. The thing is after upgraded to 1.67.0, the screen has been flickering/reloading constantly (every 3 or 4 mins).

**Comment by jeanp413** [comment] 2022-05-13 18:53
> the screen has been flickering/reloading constantly (every 3 or 4 mins).

ah so there's a lapse of time when the ws connection is fine before prompting to reload again, this is more strange then :thinking: 

Not sure if it will be of much help but you could enable trace logging to see if there's some more info about the error:
- run server with `--log trace`
- access vscode in the browser and add `?payload=[["verbose","true"]]` to the url example : `http://localhost:3000/?payload=[["verbose","true"]]`

**Comment by nappy** [comment] 2022-06-29 12:59
I am experiencing the same thing. I am using the official docker image with traefik. I added the logging options, but it does not really tell me a lot more:

![Capture](https://user-images.githubusercontent.com/56575/176441639-b1bfbd90-9166-4450-8067-0e005dc1dcf5.PNG)

```Server bound to 0.0.0.0:3000 (IPv4)
Extension host agent listening on 3000

[12:53:38] Remote configuration data at /home/workspace/.openvscode-server
[12:53:38] process arguments: {
  _: [],
  host: '0.0.0.0',
  'without-connection-token': true,
  'disable-websocket-compression': false,
  'print-startup-performance': false,
  'print-ip-address': false,
  'accept-server-license-terms': false,
  'enable-smoke-test-driver': false,
  'disable-telemetry': false,
  'disable-workspace-trust': false,
  log: 'trace',
  'force-disable-user-env': false,
  'enable-sync': false,
  'list-extensions': false,
  'show-versions': false,
  force: false,
  'do-not-sync': false,
  'pre-release': false,
  'start-server': false,
  'enable-remote-auto-shutdown': false,
  'remote-auto-shutdown-without-delay': false,
  'use-host-proxy': false,
  'without-browser-env-var': false,
  help: false,
  version: false,
  'user-data-dir': '/home/workspace/.openvscode-server/data',
  'builtin-extensions-dir': '/home/.openvscode-server/extensions',
  'extensions-dir': '/home/workspace/.openvscode-server/extensions',
  logsPath: '/home/workspace/.openvscode-server/data/logs/20220629T125338'
}
[12:53:38] Started scanning system extensions
[12:53:38] Started scanning user extensions
[12:53:38] resolveShellEnv(): running (macOS/Linux)
[12:53:38] getUnixShellEnvironment#runAsNode undefined
[12:53:38] getUnixShellEnvironment#noAttach undefined
[12:53:38] getUnixShellEnvironment#env {
  GIT_EDITOR: 'code --wait',
  HOSTNAME: '16f42148fe38',
  OPENVSCODE_SERVER_ROOT: '/home/.openvscode-server',
  HOME: '/home/workspace',
  VISUAL: 'code',
  PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  LANG: 'C.UTF-8',
  LC_ALL: 'C.UTF-8',
  PWD: '/home/workspace',
  EDITOR: 'code',
  VSCODE_HANDLES_SIGPIPE: 'true',
  ELECTRON_RUN_AS_NODE: '1',
  ELECTRON_NO_ATTACH_CONSOLE: '1'
}
[12:53:38] getUnixShellEnvironment#shell /bin/bash
[12:53:38] getUnixShellEnvironment#spawn ["-ilc"] '/home/.openvscode-server/node'  -p '"5ce957e3c9d7" + JSON.stringify(process.env) + "5ce957e3c9d7"'
Web UI available at http://localhost:3000/
[12:53:38] Extension host agent started.
[12:53:38] [File Watcher (node.js)] Request to start watching: /home/workspace/.openvscode-server/data/Machine (excludes: <none>, includes: <all>),/home/workspace/.openvscode-server/data/Machine/settings.json (excludes: <none>, includes: <all>),/home/workspace/.openvscode-server/extensions (excludes: <none>, includes: <all>)
[12:53:38] Started scanning user extensions
[12:53:38] getUnixShellEnvironment#raw 5ce957e3c9d7{"HOSTNAME":"16f42148fe38","ELECTRON_RUN_AS_NODE":"1","EDITOR":"code","PWD":"/home/workspace","HOME":"/home/workspace","LANG":"C.UTF-8","VSCODE_HANDLES_SIGPIPE":"true","OPENVSCODE_SERVER_ROOT":"/home/.openvscode-server","VISUAL":"code","SHLVL":"0","GIT_EDITOR":"code --wait","LC_ALL":"C.UTF-8","ELECTRON_NO_ATTACH_CONSOLE":"1","PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","_":"/home/.openvscode-server/node"}5ce957e3c9d7

[12:53:38] getUnixShellEnvironment#stderr bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

[12:53:38] getUnixShellEnvironment#result {
  HOSTNAME: '16f42148fe38',
  EDITOR: 'code',
  PWD: '/home/workspace',
  HOME: '/home/workspace',
  LANG: 'C.UTF-8',
  VSCODE_HANDLES_SIGPIPE: 'true',
  OPENVSCODE_SERVER_ROOT: '/home/.openvscode-server',
  VISUAL: 'code',
  SHLVL: '0',
  GIT_EDITOR: 'code --wait',
  LC_ALL: 'C.UTF-8',
  PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  _: '/home/.openvscode-server/node'
}
[12:53:38] [File Watcher (node.js)] Started watching: '/home/workspace/.openvscode-server/extensions'
[12:53:38] [File Watcher (node.js)] Started watching: '/home/workspace/.openvscode-server/data/Machine'
[12:53:38] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/workspace/.openvscode-server/data/Machine/settings.json'
[12:53:38] Scanned system extensions: 88
[12:53:38] [172.20.0.5][054b4908] Client refused: version mismatch.
[12:53:38] Scanned user extensions: 19
[12:53:38] Started scanning user extensions
[12:53:38] ComputeTargetPlatform: linux-x64
[12:53:38] Scanned user extensions: 19
[12:53:38] Overwriting system extension /home/.openvscode-server/extensions/ms-vscode.js-debug-companion with /home/workspace/.openvscode-server/extensions/ms-vscode.js-debug-companion-1.0.18.
[12:53:38] Overwriting system extension /home/.openvscode-server/extensions/clojure with /home/workspace/.openvscode-server/extensions/vscode.clojure-1.62.3.
[12:53:38] Overwriting system extension /home/.openvscode-server/extensions/cpp with /home/workspace/.openvscode-server/extensions/vscode.cpp-1.62.3.
[12:53:38] Overwriting system extension /home/.openvscode-server/extensions/html with /home/workspace/.openvscode-server/extensions/vscode.html-1.62.3.
[12:53:38] Overwriting system extension /home/.openvscode-server/extensions/ini with /home/workspace/.openvscode-server/extensions/vscode.ini-1.62.3.
[12:53:38] Overwriting system extension /home/.openvscode-server/extensions/java with /home/workspace/.openvscode-server/extensions/vscode.java-1.62.3.
[12:53:38] Overwriting system extension /home/.openvscode-server/extensions/javascript with /home/workspace/.openvscode-server/extensions/vscode.javascript-1.62.3.
[12:53:38] Overwriting system extension /home/.openvscode-server/extensions/ruby with /home/workspace/.openvscode-server/extensions/vscode.ruby-1.62.3.
[12:53:38] Overwriting system extension /home/.openvscode-server/extensions/xml with /home/workspace/.openvscode-server/extensions/vscode.xml-1.62.3.
[12:53:39] Scanned user extensions: 19
[12:53:41] [172.20.0.5][118008f1][ManagementConnection] New connection established.
[12:53:41] Started scanning system extensions
[12:53:41] Started scanning user extensions
[12:53:41] ExtensionManagementService.refreshReportedCache
Overwriting extension /home/.openvscode-server/extensions/ms-vscode.js-debug-companion with /home/workspace/.openvscode-server/extensions/ms-vscode.js-debug-companion-1.0.18.
Overwriting extension /home/.openvscode-server/extensions/clojure with /home/workspace/.openvscode-server/extensions/vscode.clojure-1.62.3.
Overwriting extension /home/.openvscode-server/extensions/cpp with /home/workspace/.openvscode-server/extensions/vscode.cpp-1.62.3.
Overwriting extension /home/.openvscode-server/extensions/html with /home/workspace/.openvscode-server/extensions/vscode.html-1.62.3.
Overwriting extension /home/.openvscode-server/extensions/ini with /home/workspace/.openvscode-server/extensions/vscode.ini-1.62.3.
Overwriting extension /home/.openvscode-server/extensions/java with /home/workspace/.openvscode-server/extensions/vscode.java-1.62.3.
Overwriting extension /home/.openvscode-server/extensions/javascript with /home/workspace/.openvscode-server/extensions/vscode.javascript-1.62.3.
Overwriting extension /home/.openvscode-server/extensions/ruby with /home/workspace/.openvscode-server/extensions/vscode.ruby-1.62.3.
Overwriting extension /home/.openvscode-server/extensions/xml with /home/workspace/.openvscode-server/extensions/vscode.xml-1.62.3.
[12:53:41] [172.20.0.5][d603b6fc][ExtensionHostConnection] New connection established.
[12:53:41] [172.20.0.5][d603b6fc][ExtensionHostConnection] <42> Launched Extension Host Process.
[12:55:32] [172.20.0.5][118008f1][ManagementConnection] The client has reconnected.
[12:57:12] [172.20.0.5][118008f1][ManagementConnection] The client has reconnected.```

**Comment by nappy** [comment] 2022-06-30 01:26
Thanks for your reply @jeanp413 According to https://github.com/traefik/traefik/issues/8668 they do not use any timeouts on websocket connections, but I have also Cloudflare enabled. I will try the idle timeout option and without Cloudflare and report back, might take a day though.

**Comment by nappy** [comment] 2022-06-30 12:25
@jeanp413 I just googled, that indeed Cloudflare is using a 100sec timeout for their non-enterprise appliances. Currently I am only using Cloudflare to be able to connect from ipv4 to my CG-NAT consumer internet home server, therefore turing it off is not really an option if i want to be able to acces from v4 only networks unfortunately.

But maybe, given that cloudflare is pretty common nowadays, maybe it would make sense to be able to configure a keep-alive ping interval. I know from my experience with XMPP, it is pretty common to implement such things for connections, that should remain active, even if there is no communication.

**Comment by jeanp413** [comment] 2022-07-01 02:31
I found the PR that caused this change in behavior https://github.com/microsoft/vscode/pull/146271, it was an event that was firing too often and it was working as a heartbeat as a side effect.
We try to make the minimal changes to upstream code so we don't have too much work with merge conflicts, so I suggest to create an issue upstream first https://github.com/microsoft/vscode/issues, asking to add a new option to the server so it sends a keep-alive event.
I'll close this issue now that we know the root cause.

**Closed by jeanp413** 2022-07-01 02:31 UTC

**Comment by jeanp413** [comment] 2022-07-01 15:37
>  the dialog/reload behavior, is that also part of upstream,

yes that's also an upstream feature
