### ISSUE TITLE
base url support

### ISSUE THREAD

**Issue by chartera** [gitpod-io/openvscode-server#320] opened 2022-03-06 15:03 UTC
It would be great to use it at another HTTP path, instead of /. 
I wanna run it behind proxy and not setup a separate sudomain for it.

**Comment by ffleandro** [comment] 2022-03-09 15:07
+1 on this

**Comment by jeanp413** [comment] 2022-03-09 20:46
@chartera @ffleandro The purpose of this project is to the minimal changes on upstream code, for this feature request you should open an issue in upstream repo https://github.com/microsoft/vscode/issues
Having said that, some time ago @wrexroad [was looking to do this too](https://github.com/gitpod-io/openvscode-server/discussions/290#discussioncomment-1972897), he needed to update some files and I think he got it working, you can take a look at this commit https://github.com/wrexroad/openvscode-server/commit/e89a148d79e53420dbb53c23e1e932d701a839b3
You can build the release version using `yarn && yarn gulp vscode-reh-web-linux-x64-min`

**Comment by wrexroad** [comment] 2022-03-10 03:38
I did get it working for the most part but I'm honestly not sure if that commit has all of the needed changes. A lot of what I did was hacking on the minified js then finding the relevant bits to change in the source. I had planned to figure out exactly what needed to be changed and send the appropriate pull requests once I had I working, but became distracted with other work. I will get back to it and put together a pull request (hopefully) by next week.

It looks like the changes could be easily made upstream, but if they aren't receptive I think the maintainers here should consider implementing something. It would be a pretty minor patch and it would be more value to the users of `code-sever` than upstream `code`.

**Comment by wrexroad** [comment] 2022-03-21 20:32
For what it's worth I did spend some time trying to get this done last week, but ran out of time. Turns out doing things right takes more time than just making something work for my own purposes... I should have more time in a day or two to work on it again.

**Comment by jeanp413** [comment] 2022-05-09 05:18
I've seen some commits recently https://github.com/microsoft/vscode/pull/147311 https://github.com/microsoft/vscode/pull/148707 that I think will enable this in the next release.
I have not tested it yet but I think you'll only need to change this line https://github.com/microsoft/vscode/blob/d9e91c33351c051876c731485a0c47a5852b904b/src/vs/platform/remote/common/remoteHosts.ts#L34 and set it your desired path

**Comment by TiemenSch** [comment] 2022-05-25 13:42
I've been trying to work around this by installing nginx in the Docker image, but I'm struggling to get it to work with some rewrites or redirects as a temporary workaround. Anyone got that to work?

**Comment by jhgoebbert** [comment] 2022-06-28 17:55
> I've seen some commits recently [microsoft#147311](https://github.com/microsoft/vscode/pull/147311) [microsoft#148707](https://github.com/microsoft/vscode/pull/148707) that I think will enable this in the next release. I have not tested it yet but I think you'll only need to change this line https://github.com/microsoft/vscode/blob/d9e91c33351c051876c731485a0c47a5852b904b/src/vs/platform/remote/common/remoteHosts.ts#L34 and set it your desired path

What if that path dynamically changes depending on the user and other things? This looks to me as if the path must be fixed.
I ask this question because I would like to integrate OpenVSCode-Server in [JupyterLab](https://jupyter.org/) - see https://github.com/gitpod-io/openvscode-server/issues/371 - which users can start by logging in through [JupyterHub](https://github.com/jupyterhub/jupyterhub). In that case a URL would look like: 
`https://jupyter-jsc-staging.fz-juelich.de/user/j.goebbert.fz-juelich.de/de47c0193b364c36b9da34e681f14911/openvscodeserver`
which depends on the user-id and some hash and therefore changes with every new login & user.

**Comment by kathoef** [comment] 2022-09-27 09:50
I also stumbled across this problem... maybe one should mention that there is also a Visual Studio Code distribution [code-server](https://github.com/coder/code-server), which has [patches applied](https://github.com/coder/code-server/blob/3264187419abc0e3c6c1519af55223be5702c9e8/patches/base-path.diff) (see also [these search results](https://github.com/coder/code-server/search?q=baseUrl)) that make Visual Studio Code accessible on arbitrary base URLs, i.e. behind reverse proxies such as [jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy). I think, I will be using that one for now.

**Comment by jhgoebbert** [comment] 2022-09-27 09:58
Yes, this is definitely an option. At the moment this does not work yet for other reasons:  
https://github.com/jupyterhub/jupyter-server-proxy/pull/337#issuecomment-1154423773

**Comment by rokroskar** [comment] 2022-09-28 07:16
@jhgoebbert @kathoef running code-server behind the jupyter-server-proxy works - but did you have some other aspect of the functionality in mind that is currently missing?

**Comment by jhgoebbert** [comment] 2022-09-28 08:09
Cool! This are great news and must be a new feature.
At least until end of June it was not possible to run a code-server behind a jupyter-server-proxy. So the issue which I described here https://github.com/gitpod-io/openvscode-server/issues/320#issuecomment-1169044927 is fixed?

**Comment by rokroskar** [comment] 2022-09-28 14:35
@jhgoebbert if you're talking about code-server (i.e. as per the comment by @kathoef above) then yes - we've been using it for a while now and it _mostly_ works. Often the jupyter/python extension breaks because of some version incompatibility which requires us to do some maintenance. We use the little jupyter-server-extension wrapper: https://github.com/betatim/vscode-binder. You can find the simple script we use [here](https://github.com/SwissDataScienceCenter/renkulab-docker/blob/master/scripts/install-vscode.sh). You can see an example project [here](https://renkulab.io/projects/rok.roskar/renku-mls-plugin/). 

We would prefer to use vscode directly to avoid issues with extensions, which is why I'm following this thread ;)

**Comment by jhgoebbert** [comment] 2022-09-29 06:20
Thank you @rokroskar 
I am wondering if this kind of setup is secure on a multi-user system like we have. There is no access-token or password required in the solution of https://github.com/betatim/vscode-binder so any user who has access to the specific port on which the vscode is listening has full control over some others account. 🤔 
Using a Unix socket instead of a port can solve this issue - but jupyter-server-proxy/tornado does not support it, yet. Or I would need to start vscode with an access token in the URL (which would be the simplest solution). I will give it another try in the next weeks 👍

**Comment by mering** [comment] 2024-03-23 12:28
Upstream added support for `--server-base-path` in microsoft/vscode#202491. How can I use it with openvscode-server?

**Comment by jeanp413** [comment] 2024-03-23 17:17
@mering you can use the [openvscode-server-insiders](https://github.com/gitpod-io/openvscode-server/releases/tag/openvscode-server-insiders-v1.88.0) release or wait until the next stable release which should be released early april

**Comment by jeanp413** [comment] 2024-03-23 17:17
closing as it got implemented upstream

**Closed by jeanp413** 2024-03-23 17:17 UTC

**Comment by mering** [comment] 2024-03-23 17:19
As I noted in https://github.com/microsoft/vscode/pull/202491#issuecomment-2016542917, this does not add the necessary functionality to work behind a proxy.

**Comment by mering** [comment] 2024-03-23 17:42
@jeanp413 can you please re-open as the requested feature is not implemented upstream. Only some other functionality which could allow a smaller downstream patch.

**Comment by jeanp413** [comment] 2024-03-24 01:47
This issue is about base path support which the upstream PR added, any additional feature request should be done in the upstream repo as noted in my previous comment https://github.com/gitpod-io/openvscode-server/issues/320#issuecomment-1063355592

**Comment by mering** [comment] 2024-03-24 06:25
Quoting the issue description:
> I wanna run it behind proxy and not setup a separate sudomain for it.

I tried to achieve exactly this (proxy which redirects `/subpath` to `container:port/`) with the latest insiders build and the new flag but couldn't get it working (and it was confirmed by upstream that this use case is not supported).

@jeanp413 so can you please re-open this issue?

**Comment by Fhwang0926** [comment] 2024-04-16 17:19
https://github.com/gitpod-io/openvscode-server/issues/336#issuecomment-2059566637

in case, using dynamic port expose with docker container, using reverse proxy by nginx

**Comment by mering** [comment] 2024-07-28 22:05
I created https://github.com/microsoft/vscode/issues/210399.
