### ISSUE TITLE
insiders-v1.64.0-linux-x64 does not run

### ISSUE THREAD

**Issue by kristsm** [gitpod-io/openvscode-server#304] opened 2022-02-03 06:51 UTC
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: v1.64.0
- OS Version: Ubuntu WSL2 (same problem with same build from docker w/wsl2 backend )

Steps to Reproduce:

1.  running ./bin/openvscode-server starts the server, but the web page is not served.  
2. Same problem if v1.64.0 insiders is run from the docker. 
Switching to latest v1.63.2-linux-x64 which is working fine (although it does not provide command: --without-connection-token, which is crucial for me ( it's necessary to run the openvscode from IPAD / SAFARI which otherwise messes up the url deleting token when running PWA from desktop.

**Comment by filiptronicek** [comment] 2022-02-04 09:30
Hi @kristsm 👋, thanks for reporting the issue. I just tried on my Windows laptop and couldn't reproduce. This might be because we made many changes which we ported from upstream (microsoft/vscode), could you please try again on the https://github.com/gitpod-io/openvscode-server/releases/tag/openvscode-server-insiders-v1.65.0 and let me know whether anything changed? 
![image](https://user-images.githubusercontent.com/29888641/152505141-fe65cf45-8256-43ee-a22e-6a027a0d54ff.png)

**Comment by kristsm** [comment] 2022-02-04 17:53
Thanks for the reply!

OK, this is getting weird - WSL2 refuses to server openvscode-server  webpage for insiders-v1.65.0  and also for newest latest v1.64.0. I also tried armhf builds on RPI and same - connection refused.  V1.63.2 runs without problems both on WSL2 /docker and also on armhf soc. 
For v1.65.0 & v1.64.0 I just untar to the folder and hit ./bin/openvscode-server:

Extension host agent listening on 3000

Web UI available at http://localhost:3000/?tkn=74861987-7aac-446d-b067-aa4366bce458
[19:51:39] Extension host agent started.
[19:51:45] No ptyHost heartbeat after 6 seconds

On web page - 
This site can’t be reached
192.168.8.223 refused to connect.

**Comment by aptalca** [comment] 2022-02-04 19:16
Hi, I'm one of the linuxserver.io devs and the maintainer of our docker image.

I'm also experiencing the same issue. After updating the service to call the new script `bin/openvscode-server`, the log entries seem fine, the same as they did for the previous versions, but no web connection can be made. Chrome simply reports `localhost didn’t send any data.` and `ERR_EMPTY_RESPONSE`.

I tried with and without connection tokens with the same result.

What's interesting is, if I `curl http://localhost:3000` from inside the container, everything's well. Only if I try to connect from outside the container, it refuses to accept any connection.

This is the same behavior with both 1.64.0 and the insiders 1.65.0

Thanks

**Comment by aptalca** [comment] 2022-02-04 19:28
I had to set `--host 0.0.0.0` because apparently it defaults to `localhost` so it won't accept any connections from outside the container

**Comment by filiptronicek** [comment] 2022-02-04 20:33
https://github.com/microsoft/vscode/commit/7af01231419a27c7fdef3032275f9ea054544042 stands out as a possible cause, as it's changing the default host from `127.0.0.1` to `localhost`.

Thanks @aptalca for the suggestion, if it helps, we will document it so that this behavior will be more clear.

**Comment by kristsm** [comment] 2022-02-04 20:36
@aptalca thank you sir! Everything flies now! :)

**Comment by jeanp413** [comment] 2022-02-05 03:03
@filiptronicek feel free to close this and/or create a PR documenting that by default the server listens on localhost

**Comment by kristsm** [comment] 2022-02-05 14:17
I'd like to share with you another situation:  I installed V1.63.0, V1.64 and insiders-V1.65.0  all ARMHF versions  on raspberry pi. V1.63.0 runs out of the box. V1.64 and V1.65-insiders runs only with --host  0.0.0.0. But when V1.64 or V1.65-insiders are run with --no-connection-token, web page is not served ( browser shows - forbidden). 

Any ideas?

**Comment by jeanp413** [comment] 2022-02-05 14:34
@kristsm are you using both `--host 0.0.0.0 --no-connection-token` or just `--no-connection-token`

**Comment by kristsm** [comment] 2022-02-05 15:22
With generated token it's running fine. Error occurs only when tokens are turned off.

**Comment by jeanp413** [comment] 2022-02-05 15:48
When you run the server with `--host 0.0.0.0 --without-connection-token`, in the console logs do you see something like this `Web UI available at http://localhost:3000/` or `http://localhost:9888/?tkn=3036580052` if the latter maybe you miss-typed the flag

**Comment by kristsm** [comment] 2022-02-05 15:54
> When you run the server with `--host 0.0.0.0 --without-connection-token`, in the console logs do you see something like this `Web UI available at http://localhost:3000/` or `http://localhost:3000/?tkn=3036580052` if the latter maybe you miss-typed the flag

Yes, that is what I see. Same as if run without token off.  But the web page is not provided ( browser shows - forbidden)

**Comment by kristsm** [comment] 2022-02-05 17:42
Btw, perhaps it's possible in the future to restrict  the program and warn the user about invalid options ( at least it's usual praxis)?
 Because the problem here was that I didn't even notice the  error and the program just ignored that invalid option and went further  by default settings  :)

**Closed** 2022-02-07 19:48 UTC
Labels: bug
