### ISSUE TITLE
sudo: command not found

### ISSUE THREAD

**Issue by AyaanZaveri** [gitpod-io/openvscode-server#109] opened 2021-09-30 00:21 UTC
I deployed the server on Railway and it says "sudo: command not found" when I'm trying to install a package via apt. [Code-Server](https://github.com/cdr/code-server/) didn't have this issue when being deployed on Railway. Is there a solution for this?

**Comment by im-coder-lg** [comment] 2021-09-30 03:51
wow, @AyaanZaveri I have the exact same error! I am really used to `sudo` but the Code Web server just doesn't allow me. I don't even know the password! I have the sudo error as well as this:
```console
vscode-server@railway:~$ sudo apt install neofetch zsh
bash: sudo: command not found
vscode-server@railway:~$ apt install neofetch zsh
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```
> Code-Server didn't have this issue when being deployed on Railway.

You are right. code-server never had the sudo error. I am used to sudo that now I can't even log in as root, the `sudo su` command doesn't work. Even the `su` command needs a password, which I don't know. Even `echo $PASSWD` doesn't work. Can anybody look at this?

**Comment by im-coder-lg** [comment] 2021-09-30 03:52
I can't install Neofetch and ZSH but if I need to use ZSH with Focal Fossa, it doesn't help it. This is supposedly a Docker image, so let me try something about this.

**Comment by im-coder-lg** [comment] 2021-09-30 03:57
Moreover, the entire image runs on a Bionic Beaver server, and it is of no use for upgrading, since it's a fail

**Comment by ghuntley** [comment] 2021-09-30 04:12
Duplicate of #87. For now you can mitigate by building your own docker image as follows:

```docker
FROM gitpod-io/openvscode-server

# Configure sudo
RUN apt-get update \ 
    && apt-get install -y sudo \
    && adduser vscode-server sudo \
    && sed -i.bkp -e 's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' /etc/sudoers
```

**Closed by ghuntley** 2021-09-30 04:12 UTC

**Comment by im-coder-lg** [comment] 2021-09-30 04:13
wait @ghuntley do I need to add extra code there?

**Comment by im-coder-lg** [comment] 2021-09-30 04:27
it's failed. How can I log in to Docker via a Dockerfile? The build logs I had was all this only:
```console
Sending build context to Docker daemon  27.14kB

Step 1/19 : FROM gitpod-io/openvscode-server
pull access denied for gitpod-io/openvscode-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by ghuntley** [comment] 2021-09-30 04:38
Apologies for the typos and ommoisions. Have updated above and tested.

<img width="1136" alt="2021-09-30_14-37-44" src="https://user-images.githubusercontent.com/127353/135388207-cc2fdde2-912e-4746-aabd-736506e8ef92.png">

**Comment by im-coder-lg** [comment] 2021-09-30 04:41
wow, next fail. The Docker layer was pulled but this didn't work
```console
==========================
Using detected Dockerfile!
==========================

Sending build context to Docker daemon  27.14kB

Step 1/19 : FROM gitpod/openvscode-server
latest: Pulling from gitpod/openvscode-server
e4ca327ec0e7: Already exists
5639b911a945: Pulling fs layer
5354ed932f0c: Pulling fs layer
4f4fb700ef54: Pulling fs layer
dd4926857739: Pulling fs layer
016af3f774b4: Pulling fs layer
dd0c0ade306d: Pulling fs layer
4bf060175a5c: Pulling fs layer
016af3f774b4: Waiting
dd0c0ade306d: Waiting
4bf060175a5c: Waiting
dd4926857739: Waiting
4f4fb700ef54: Download complete
5639b911a945: Verifying Checksum
5639b911a945: Download complete
5354ed932f0c: Verifying Checksum
5354ed932f0c: Download complete
dd0c0ade306d: Download complete
dd4926857739: Verifying Checksum
dd4926857739: Download complete
016af3f774b4: Verifying Checksum
016af3f774b4: Download complete
5639b911a945: Pull complete
4bf060175a5c: Verifying Checksum
4bf060175a5c: Download complete
5354ed932f0c: Pull complete
4f4fb700ef54: Pull complete
dd4926857739: Pull complete
016af3f774b4: Pull complete
dd0c0ade306d: Pull complete
4bf060175a5c: Pull complete
Digest: sha256:56c4d271800d117af2f32c4edf3cf674821803be79ca8d64f650eb40ade44abe
Status: Downloaded newer image for gitpod/openvscode-server:latest
 ---> 4bb37514bda5
Step 2/19 : RUN apt-get update     && apt-get install -y sudo     && adduser vscode-server sudo     && sed -i.bkp -e 's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' /etc/sudoers
 ---> Running in e48108db5127
Reading package lists...
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
The command '/bin/sh -c apt-get update     && apt-get install -y sudo     && adduser vscode-server sudo     && sed -i.bkp -e 's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' /etc/sudoers' returned a non-zero code: 100
```

**Comment by ghuntley** [comment] 2021-09-30 04:48
Did you include the `USER root` line?

**Comment by im-coder-lg** [comment] 2021-09-30 05:09
no, should I do it?

**Comment by im-coder-lg** [comment] 2021-09-30 05:09
Let me try that.

**Comment by im-coder-lg** [comment] 2021-09-30 05:15
Nah, doesn't work and the log is really big.

**Comment by jeanp413** [comment] 2021-09-30 17:41
@AyaanZaveri @im-coder-lg updated the docker images with sudo support.
